### ISSUE TITLE
Enable Gitlab CI/CD for github repository

### ISSUE THREAD

**Issue by jocelynthode** [simonbru/ocurl-django#6]
I suggest we use gitlab CI for this project.

https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html

**Comment by jocelynthode** [comment]
@simonbru I'll try to create a gitlab-ci.yml file once we are integrated if this works for you

**Comment by simonbru** [comment]
I'm *chaud2ouf*
